version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pharmacy_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pharmacy
      MYSQL_USER: userl
      MYSQL_PASSWORD: userp
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
